// ─────────────────────────────────────────────────────────────────────────────
// TOP 1% — CREATOR INTELLIGENCE DATABASE
// Full prestige creator roster + biological hook scoring system
// ─────────────────────────────────────────────────────────────────────────────

export const PRESTIGE_CREATORS = [
  // ── COMMUNICATION & PRESENCE ──────────────────────────────────────────────
  {
    name: "Vinh Giang",
    channelId: "UCmJJut8kMS_OzqmNAmAYm8A",
    category: "Communication",
    tier: 1,
    hookStrength: 98,
    authorityType: "Vocal Mastery",
    triggerType: "revelation",
    vpsRating: 95,
    audienceAge: "25-45",
    why: "Master of vocal delivery and showmanship. Every clip demonstrates a tangible skill instantly.",
    searchKeywords: ["communication", "public speaking", "vocal delivery", "confidence"],
    postFrequency: "weekly",
    avgViews: 80000,
  },
  {
    name: "Jefferson Fisher",
    channelId: "UCLMnbEUPEJBGFUQaERSPukg",
    category: "Communication",
    tier: 1,
    hookStrength: 99,
    authorityType: "Legal Authority",
    triggerType: "challenge",
    vpsRating: 99,
    audienceAge: "22-55",
    why: "Trial lawyer giving 60-second masterclasses on arguing. Straight-to-camera creates instant trust and urgency.",
    searchKeywords: ["how to respond", "argument", "communication", "lawyer advice"],
    postFrequency: "daily",
    avgViews: 500000,
  },
  {
    name: "Charisma on Command",
    channelId: "UCU_W0oE_ock8bWKjALiGs8Q",
    category: "Charisma & Social Skills",
    tier: 1,
    hookStrength: 96,
    authorityType: "Celebrity Deconstruction",
    triggerType: "curiosity",
    vpsRating: 94,
    audienceAge: "18-35",
    why: "Breaks down why celebrities are likable. Makes viewer feel they're getting insider knowledge.",
    searchKeywords: ["charisma", "confidence", "social skills", "likability"],
    postFrequency: "weekly",
    avgViews: 300000,
  },
  {
    name: "Julian Treasure",
    channelId: "UCMpKQADdIoeSKfMCDqEJQEg",
    category: "Communication",
    tier: 1,
    hookStrength: 97,
    authorityType: "Academic Prestige",
    triggerType: "revelation",
    vpsRating: 96,
    audienceAge: "28-55",
    why: "Famous TED Talk speaker on how to speak so people want to listen. Instant prestige recognition.",
    searchKeywords: ["how to speak", "voice", "communication", "TED"],
    postFrequency: "monthly",
    avgViews: 150000,
  },
  {
    name: "Vanessa Van Edwards",
    channelId: "UCgVhWuFRBdMxK6K5SHW24Ug",
    category: "Body Language & Psychology",
    tier: 1,
    hookStrength: 96,
    authorityType: "Science-Based Authority",
    triggerType: "revelation",
    vpsRating: 93,
    audienceAge: "22-45",
    why: "Science-based communication. Body language clips are click-magnets for every demographic.",
    searchKeywords: ["body language", "first impression", "nonverbal", "charisma"],
    postFrequency: "weekly",
    avgViews: 200000,
  },
  {
    name: "Amy Cuddy",
    channelId: "UCMvIBGCT4RFBhEsKNJHg1bQ",
    category: "Presence & Psychology",
    tier: 1,
    hookStrength: 94,
    authorityType: "Academic Prestige",
    triggerType: "inspiration",
    vpsRating: 92,
    audienceAge: "25-50",
    why: "Power posing and presence authority. TED Talk prestige makes every clip instantly credible.",
    searchKeywords: ["power pose", "confidence", "presence", "body language"],
    postFrequency: "monthly",
    avgViews: 100000,
  },
  {
    name: "Chris Voss",
    channelId: "UCyZHGMrr7T7-3TIh5R1Q0_A",
    category: "Negotiation",
    tier: 1,
    hookStrength: 98,
    authorityType: "FBI Authority",
    triggerType: "revelation",
    vpsRating: 97,
    audienceAge: "28-55",
    why: "Former FBI negotiator. Clips of him teaching negotiation are incredibly sticky — real life stakes.",
    searchKeywords: ["negotiation", "FBI", "how to negotiate", "persuasion"],
    postFrequency: "weekly",
    avgViews: 250000,
  },
  {
    name: "Matt Abrahams",
    channelId: "UCMpKQADdIoeSKfMCDqEJQEg",
    category: "Communication",
    tier: 2,
    hookStrength: 93,
    authorityType: "Academic Prestige",
    triggerType: "revelation",
    vpsRating: 94,
    audienceAge: "28-55",
    why: "Stanford GSB. Think Fast Talk Smart. Academic prestige bypasses viewer skepticism instantly.",
    searchKeywords: ["think fast talk smart", "Stanford", "public speaking", "communication"],
    postFrequency: "weekly",
    avgViews: 80000,
  },

  // ── LEADERSHIP & BUSINESS ─────────────────────────────────────────────────
  {
    name: "Simon Sinek",
    channelId: "UCNavnFDL6tBP3bOQFhBJTww",
    category: "Leadership",
    tier: 1,
    hookStrength: 97,
    authorityType: "Philosophical Authority",
    triggerType: "revelation",
    vpsRating: 96,
    audienceAge: "28-55",
    why: "Master of The Why. Every clip is a masterclass in leadership that makes people rethink everything.",
    searchKeywords: ["leadership", "why", "purpose", "inspiration", "Simon Sinek"],
    postFrequency: "weekly",
    avgViews: 300000,
  },
  {
    name: "Brian Tracy",
    channelId: "UCvhpx2C2AZmqN_u-gLMjXxg",
    category: "Success & Leadership",
    tier: 1,
    hookStrength: 96,
    authorityType: "Legacy Authority",
    triggerType: "inspiration",
    vpsRating: 95,
    audienceAge: "30-60",
    why: "Generational authority. His content has proven staying power across 40+ years.",
    searchKeywords: ["success", "goals", "leadership", "Brian Tracy", "motivation"],
    postFrequency: "weekly",
    avgViews: 200000,
  },
  {
    name: "Steven Bartlett",
    channelId: "UCGq-4rLB8dMTQ9IZkNn1s1Q",
    category: "Business & Mindset",
    tier: 1,
    hookStrength: 99,
    authorityType: "Modern Prestige",
    triggerType: "revelation",
    vpsRating: 97,
    audienceAge: "22-40",
    why: "Diary of a CEO. Currently the most viral business interview clips on the internet.",
    searchKeywords: ["diary of a CEO", "business", "entrepreneur", "Steven Bartlett"],
    postFrequency: "weekly",
    avgViews: 2000000,
  },
  {
    name: "Alex Hormozi",
    channelId: "UCexzRBOFiLiVMnNF5P5sXXw",
    category: "Business",
    tier: 1,
    hookStrength: 99,
    authorityType: "Results Authority",
    triggerType: "challenge",
    vpsRating: 98,
    audienceAge: "22-45",
    why: "Currently the king of business content. His editing style is what everyone copies. Maximum density.",
    searchKeywords: ["Alex Hormozi", "business", "sales", "offer", "money"],
    postFrequency: "daily",
    avgViews: 1000000,
  },
  {
    name: "John C. Maxwell",
    channelId: "UCxVmFfE0ZJRD-ib1NwrLaDQ",
    category: "Leadership",
    tier: 1,
    hookStrength: 94,
    authorityType: "Classic Authority",
    triggerType: "inspiration",
    vpsRating: 93,
    audienceAge: "30-65",
    why: "The classic authority on leadership. Very clear structured speech — high VPS ratio.",
    searchKeywords: ["leadership", "Maxwell", "influence", "success"],
    postFrequency: "weekly",
    avgViews: 150000,
  },
  {
    name: "Jocko Willink",
    channelId: "UCkqcY4CAuBFNFho6JgygCnA",
    category: "Discipline & Leadership",
    tier: 1,
    hookStrength: 98,
    authorityType: "Military Authority",
    triggerType: "challenge",
    vpsRating: 97,
    audienceAge: "22-45",
    why: "Extreme ownership. High-intensity, high-authority clips. Stops any man mid-scroll immediately.",
    searchKeywords: ["Jocko", "discipline", "ownership", "military", "leadership"],
    postFrequency: "daily",
    avgViews: 400000,
  },
  {
    name: "Robin Sharma",
    channelId: "UCxhHHBDExZtRlUTFI6oX3Ag",
    category: "Leadership & Lifestyle",
    tier: 2,
    hookStrength: 93,
    authorityType: "Lifestyle Authority",
    triggerType: "inspiration",
    vpsRating: 91,
    audienceAge: "28-55",
    why: "World-class leadership and 5AM Club. Aspirational content that makes people want to change.",
    searchKeywords: ["Robin Sharma", "5am club", "leadership", "excellence"],
    postFrequency: "weekly",
    avgViews: 100000,
  },
  {
    name: "Patrick Lencioni",
    channelId: "UCh_ugKacslKhsRs9n4OzDjA",
    category: "Business Leadership",
    tier: 2,
    hookStrength: 91,
    authorityType: "Executive Storytelling",
    triggerType: "revelation",
    vpsRating: 92,
    audienceAge: "30-55",
    why: "Expert at storytelling for executive teams. B2B content with massive LinkedIn potential.",
    searchKeywords: ["team dysfunction", "leadership", "executive", "business"],
    postFrequency: "monthly",
    avgViews: 60000,
  },

  // ── MINDSET & PERFORMANCE ─────────────────────────────────────────────────
  {
    name: "David Goggins",
    channelId: "UCcaRHDxBsHWgQZBfKEfqgcw",
    category: "Mental Toughness",
    tier: 1,
    hookStrength: 100,
    authorityType: "Lived Experience Authority",
    triggerType: "challenge",
    vpsRating: 98,
    audienceAge: "18-45",
    why: "If you want someone to leave whatever they are doing — this is the guy. Pure intensity that freezes scrollers.",
    searchKeywords: ["David Goggins", "discipline", "mental toughness", "hard"],
    postFrequency: "weekly",
    avgViews: 1500000,
  },
  {
    name: "Mel Robbins",
    channelId: "UCk2u5u-YKXbM1dE5BpBZoGA",
    category: "Mindset & Action",
    tier: 1,
    hookStrength: 97,
    authorityType: "Methodology Authority",
    triggerType: "challenge",
    vpsRating: 96,
    audienceAge: "25-50",
    why: "Famous for the 5-Second Rule. High-energy delivery that physically stops people from scrolling.",
    searchKeywords: ["5 second rule", "Mel Robbins", "motivation", "mindset"],
    postFrequency: "daily",
    avgViews: 500000,
  },
  {
    name: "James Clear",
    channelId: "UCSmzukKZhgCJCFIRmQe1GhQ",
    category: "Habits & Systems",
    tier: 1,
    hookStrength: 96,
    authorityType: "Scientific Methodology",
    triggerType: "revelation",
    vpsRating: 97,
    audienceAge: "22-45",
    why: "Atomic Habits author. Short punchy wisdom on systems — every sentence could be a viral clip.",
    searchKeywords: ["atomic habits", "James Clear", "habits", "systems", "improvement"],
    postFrequency: "monthly",
    avgViews: 300000,
  },
  {
    name: "Andrew Huberman",
    channelId: "UC2D2CMWXMOVWx7giW1n3LIg",
    category: "Neuroscience & Performance",
    tier: 1,
    hookStrength: 97,
    authorityType: "Academic Prestige",
    triggerType: "revelation",
    vpsRating: 95,
    audienceAge: "25-50",
    why: "Science-based tools for the brain. Academic background gives instant authority. Everyone shares his clips.",
    searchKeywords: ["Huberman", "neuroscience", "performance", "brain", "dopamine"],
    postFrequency: "weekly",
    avgViews: 800000,
  },
  {
    name: "Les Brown",
    channelId: "UCgsB-5F9GxLJKq6pHq7QH1g",
    category: "Motivation & Mindset",
    tier: 1,
    hookStrength: 97,
    authorityType: "Legacy Oratory",
    triggerType: "inspiration",
    vpsRating: 96,
    audienceAge: "22-65",
    why: "Generational motivational speaker. His voice alone stops people. Every clip is emotionally charged.",
    searchKeywords: ["Les Brown", "motivation", "greatness", "mindset"],
    postFrequency: "weekly",
    avgViews: 500000,
  },
  {
    name: "Ryan Holiday",
    channelId: "UCJuQLx3mBjPBdFTCXqIWbZA",
    category: "Stoicism & Philosophy",
    tier: 1,
    hookStrength: 95,
    authorityType: "Philosophical Authority",
    triggerType: "revelation",
    vpsRating: 96,
    audienceAge: "25-50",
    why: "Stoicism for the modern world. Visually aesthetic, calm content that feels like wisdom.",
    searchKeywords: ["Ryan Holiday", "stoicism", "ego", "obstacle", "philosophy"],
    postFrequency: "weekly",
    avgViews: 200000,
  },
  {
    name: "Brené Brown",
    channelId: "UCGR4pMLjnNQOAFSZBp0K_YQ",
    category: "Vulnerability & Psychology",
    tier: 1,
    hookStrength: 96,
    authorityType: "Research Authority",
    triggerType: "discomfort",
    vpsRating: 95,
    audienceAge: "28-55",
    why: "Authority on vulnerability and shame. Deeply emotional, high-share content — especially among women.",
    searchKeywords: ["Brene Brown", "vulnerability", "courage", "shame", "connection"],
    postFrequency: "monthly",
    avgViews: 400000,
  },
  {
    name: "Adam Grant",
    channelId: "UCwlhfxXNEGRlDa5xk-sAnpw",
    category: "Work Psychology",
    tier: 1,
    hookStrength: 95,
    authorityType: "Academic Prestige",
    triggerType: "challenge",
    vpsRating: 95,
    audienceAge: "25-50",
    why: "Organizational psychologist. WorkLife clips challenge how people think about work — extremely shareable.",
    searchKeywords: ["Adam Grant", "think again", "work", "psychology", "potential"],
    postFrequency: "weekly",
    avgViews: 300000,
  },
  {
    name: "Jim Rohn",
    channelId: "UCBcRF18a7Qf58cCRy5xuWwQ",
    category: "Life Philosophy",
    tier: 1,
    hookStrength: 96,
    authorityType: "Legacy Authority",
    triggerType: "revelation",
    vpsRating: 97,
    audienceAge: "25-65",
    why: "The original success philosopher. His clips age like gold. Shared by people wanting to seem wise.",
    searchKeywords: ["Jim Rohn", "success", "philosophy", "discipline", "life"],
    postFrequency: "archive",
    avgViews: 300000,
  },
  {
    name: "Dr. Nicole LePera",
    channelId: "UCMxQFBPFBmHFVDQBFzEhEsQ",
    category: "Healing Psychology",
    tier: 2,
    hookStrength: 95,
    authorityType: "Holistic Authority",
    triggerType: "revelation",
    vpsRating: 93,
    audienceAge: "22-45",
    why: "Master of viral healing and mindset psychology. Massive female audience. Extremely high share rate.",
    searchKeywords: ["holistic psychologist", "healing", "trauma", "self", "psychology"],
    postFrequency: "daily",
    avgViews: 500000,
  },

  // ── WEALTH & ECONOMICS ────────────────────────────────────────────────────
  {
    name: "Naval Ravikant",
    channelId: "UCh_ugKacslKhsRs9n4OzDjA",
    category: "Wealth Philosophy",
    tier: 1,
    hookStrength: 98,
    authorityType: "Silicon Valley Authority",
    triggerType: "revelation",
    vpsRating: 99,
    audienceAge: "22-45",
    why: "Every sentence Naval says is quotable. Highest value-per-second of any creator alive.",
    searchKeywords: ["Naval", "wealth", "happiness", "philosophy", "entrepreneur"],
    postFrequency: "rare",
    avgViews: 500000,
  },
  {
    name: "Morgan Housel",
    channelId: "UCzaBhs_5D0lPmQxF4Wk0YEg",
    category: "Psychology of Money",
    tier: 1,
    hookStrength: 95,
    authorityType: "Wisdom Authority",
    triggerType: "revelation",
    vpsRating: 97,
    audienceAge: "28-55",
    why: "Explains psychology of money. Calm high-wisdom clips shared by people who want to seem smart.",
    searchKeywords: ["Morgan Housel", "psychology of money", "wealth", "investing"],
    postFrequency: "monthly",
    avgViews: 150000,
  },
  {
    name: "Ramit Sethi",
    channelId: "UCCCbFvbgaFZKqvHQGHHPa6Q",
    category: "Personal Finance",
    tier: 2,
    hookStrength: 95,
    authorityType: "Confrontational Authority",
    triggerType: "challenge",
    vpsRating: 94,
    audienceAge: "22-40",
    why: "Confrontational yet helpful style. His rich life content works perfectly for shorts controversy.",
    searchKeywords: ["Ramit Sethi", "rich life", "money", "finance", "wealth"],
    postFrequency: "weekly",
    avgViews: 200000,
  },
  {
    name: "Ray Dalio",
    channelId: "UCsSe4BGNqJVoEP3FhQD9z-A",
    category: "Economics & Investing",
    tier: 1,
    hookStrength: 95,
    authorityType: "Billionaire Authority",
    triggerType: "revelation",
    vpsRating: 94,
    audienceAge: "28-60",
    why: "Billionaire explaining economic principles. Pure authority bypass of viewer skepticism.",
    searchKeywords: ["Ray Dalio", "principles", "economy", "investing", "debt cycle"],
    postFrequency: "monthly",
    avgViews: 300000,
  },
  {
    name: "Vivian Tu",
    channelId: "UCqRVxJtfXiJKNv4uYcHKkfg",
    category: "Finance",
    tier: 2,
    hookStrength: 94,
    authorityType: "Gen Z Authority",
    triggerType: "revelation",
    vpsRating: 92,
    audienceAge: "18-35",
    why: "Your Rich BFF. Fast-paced high-energy financial advice for Gen Z. Massive young audience.",
    searchKeywords: ["rich BFF", "money", "investing", "finance", "Gen Z"],
    postFrequency: "daily",
    avgViews: 300000,
  },
  {
    name: "Dave Ramsey",
    channelId: "UCQeOFAzNTZKmq3u0xX6JDOQ",
    category: "Personal Finance",
    tier: 2,
    hookStrength: 96,
    authorityType: "Controversial Authority",
    triggerType: "challenge",
    vpsRating: 93,
    audienceAge: "28-60",
    why: "Controversial, loud, and authoritative. Perfect for driving comments and debates — extreme engagement.",
    searchKeywords: ["Dave Ramsey", "debt", "baby steps", "money", "financial freedom"],
    postFrequency: "daily",
    avgViews: 400000,
  },

  // ── SOCIAL PSYCHOLOGY ─────────────────────────────────────────────────────
  {
    name: "Thomas Erikson",
    channelId: "UCvOmitckdMCDaqWBsqPdgcg",
    category: "Social Psychology",
    tier: 2,
    hookStrength: 93,
    authorityType: "Personality Science",
    triggerType: "curiosity",
    vpsRating: 92,
    audienceAge: "22-50",
    why: "Surrounded by Idiots. Personality type clips generate massive self-identification sharing.",
    searchKeywords: ["surrounded by idiots", "DISC", "personality", "behavior"],
    postFrequency: "weekly",
    avgViews: 150000,
  },
  {
    name: "Dan Koe",
    channelId: "UCXBuEDDWVaO0GjUMHT1HXOQ",
    category: "Philosophy & Creator Economy",
    tier: 2,
    hookStrength: 96,
    authorityType: "Visual Philosophy",
    triggerType: "revelation",
    vpsRating: 95,
    audienceAge: "18-35",
    why: "Most visually aesthetic philosophical hooks on the internet. Extremely high share rate.",
    searchKeywords: ["Dan Koe", "one person business", "purpose", "philosophy", "creator"],
    postFrequency: "weekly",
    avgViews: 300000,
  },
  {
    name: "Tony Robbins",
    channelId: "UCz7UPZO_BtIGQKLj94oUXqg",
    category: "Human Potential",
    tier: 1,
    hookStrength: 97,
    authorityType: "Legacy Peak Performance",
    triggerType: "inspiration",
    vpsRating: 95,
    audienceAge: "25-65",
    why: "Generational peak performance authority. His voice and energy stop anyone regardless of age.",
    searchKeywords: ["Tony Robbins", "motivation", "peak state", "success", "potential"],
    postFrequency: "weekly",
    avgViews: 500000,
  },
  {
    name: "Jordan Peterson",
    channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
    category: "Psychology & Philosophy",
    tier: 1,
    hookStrength: 98,
    authorityType: "Academic Controversy",
    triggerType: "challenge",
    vpsRating: 97,
    audienceAge: "18-45",
    why: "Creates the most emotional comment sections on the internet. Controversy plus wisdom = virality.",
    searchKeywords: ["Jordan Peterson", "psychology", "meaning", "responsibility", "maps of meaning"],
    postFrequency: "weekly",
    avgViews: 1000000,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// INTELLIGENCE SCORING ENGINE
// Scores each video before surfacing to user
// ─────────────────────────────────────────────────────────────────────────────

export function scoreVideo(video, creator, details) {
  let score = 0;
  const notes = [];

  // 1. Creator hook strength (0-30 points)
  const hookPoints = Math.round((creator.hookStrength / 100) * 30);
  score += hookPoints;

  // 2. View velocity — views per day since upload (0-25 points)
  const daysSince = Math.max(1, Math.floor((Date.now() - new Date(video.publishedAt)) / 86400000));
  const viewsPerDay = (details?.viewCount || 0) / daysSince;
  const velocityScore = Math.min(25, Math.round((viewsPerDay / 10000) * 25));
  score += velocityScore;
  if (viewsPerDay > 5000) notes.push(`${Math.round(viewsPerDay).toLocaleString()} views/day`);

  // 3. Comment engagement ratio (0-20 points)
  const commentRatio = details?.viewCount > 0 ? (details?.commentCount || 0) / details.viewCount : 0;
  const commentScore = Math.min(20, Math.round(commentRatio * 2000));
  score += commentScore;
  if (commentRatio > 0.005) notes.push("High comment ratio");

  // 4. Creator tier bonus (0-15 points)
  const tierBonus = creator.tier === 1 ? 15 : creator.tier === 2 ? 9 : 5;
  score += tierBonus;

  // 5. Freshness bonus (0-10 points) — newer content performs better
  const freshnessScore = daysSince <= 1 ? 10 : daysSince <= 3 ? 8 : daysSince <= 7 ? 5 : daysSince <= 14 ? 3 : 1;
  score += freshnessScore;
  if (daysSince <= 3) notes.push(`Posted ${daysSince === 0 ? "today" : daysSince + "d ago"} — very fresh`);

  // Determine priority tier
  let priority, color;
  if (score >= 80) { priority = "MUST POST"; color = "#E8FF00"; }
  else if (score >= 65) { priority = "HIGH"; color = "#00f2ea"; }
  else if (score >= 50) { priority = "MEDIUM"; color = "#fb923c"; }
  else { priority = "LOW"; color = "#555"; }

  return {
    score: Math.min(100, score),
    priority,
    color,
    notes,
    breakdown: { hookPoints, velocityScore, commentScore, tierBonus, freshnessScore },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// OPTIMAL POSTING STRATEGY
// Platform-specific timing for maximum reach
// ─────────────────────────────────────────────────────────────────────────────

export const POSTING_STRATEGY = {
  youtube: {
    bestDays: ["Thursday", "Friday", "Saturday"],
    bestHours: [8, 12, 17, 20],
    maxPerDay: 3,
    formatNote: "9:16 vertical · 15-60 seconds · Hook in first 3s",
    hashtagStrategy: "5-8 tags, mix of broad and niche",
    titleFormula: "Curiosity gap + authority + number or outcome",
  },
  tiktok: {
    bestDays: ["Tuesday", "Thursday", "Friday"],
    bestHours: [7, 13, 19, 21],
    maxPerDay: 4,
    formatNote: "9:16 vertical · 30-60 seconds sweet spot",
    hashtagStrategy: "3-5 tags, mix trending + niche",
    titleFormula: "Shock hook + relatable problem",
  },
  instagram: {
    bestDays: ["Monday", "Wednesday", "Friday"],
    bestHours: [9, 12, 19],
    maxPerDay: 2,
    formatNote: "9:16 vertical Reels · 30-90 seconds",
    hashtagStrategy: "8-15 tags, highly targeted",
    titleFormula: "Emotional trigger + identity statement",
  },
  twitter: {
    bestDays: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    bestHours: [8, 12, 17],
    maxPerDay: 5,
    formatNote: "16:9 or 9:16 · Under 2 minutes 20 seconds",
    hashtagStrategy: "2-3 tags max",
    titleFormula: "One controversial or profound single sentence",
  },
  linkedin: {
    bestDays: ["Tuesday", "Wednesday", "Thursday"],
    bestHours: [8, 10, 17],
    maxPerDay: 1,
    formatNote: "16:9 preferred · 1-3 minutes",
    hashtagStrategy: "3-5 professional tags",
    titleFormula: "Professional insight + business outcome",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// COMPETITOR INTELLIGENCE
// What makes us different and better
// ─────────────────────────────────────────────────────────────────────────────

export const COMPETITIVE_EDGE = {
  advantages: [
    "Targeting prestige creators that already have trust — not building trust from scratch",
    "Gemini watches videos directly — no transcript errors, no lost context",
    "Biological hook scoring — only surface videos that will stop the scroll",
    "VPS (Value Per Second) optimization — every second of every clip earns attention",
    "Cross-platform SEO — each platform gets its own engineered title and caption",
    "Freshness algorithm — new content from active creators posted within 72 hours of upload",
    "Archive mining — Tier 1 legacy creators have decades of unsurfaced gold",
    "Comment engineering — first comment designed to trigger algorithm engagement",
  ],
  differentiators: [
    "Other clip channels post summaries. We post the original speaker's exact words.",
    "Other channels use one caption for all platforms. We engineer each platform separately.",
    "Other channels post when convenient. We post at peak hours algorithmically determined.",
    "Other channels guess what will perform. We score every video before posting.",
  ],
};

export default PRESTIGE_CREATORS;
